'use client';

import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Download, Loader2 } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { useToast } from '@/hooks/use-toast';
import { format } from 'date-fns';
import type { ReportData } from '@/app/actions/report';

interface AnalyticsExportButtonProps {
    data: ReportData | null;
    className?: string;
}

export function AnalyticsExportButton({ data, className }: AnalyticsExportButtonProps) {
    const [loading, setLoading] = useState(false);
    const { toast } = useToast();

    const handleExportPDF = async () => {
        if (!data) return;
        setLoading(true);

        try {
            const doc = new jsPDF();

            // Header
            doc.setFontSize(22);
            doc.text(`Sales Analytics Report`, 14, 20);

            doc.setFontSize(10);
            const dateStr = format(new Date(), 'dd MMMM yyyy HH:mm');
            doc.text(`Generated on: ${dateStr}`, 14, 28);

            // 1. TOP STATS
            doc.setFontSize(14);
            doc.setTextColor(44, 62, 80);
            doc.text("Performance Summary", 14, 40);

            // Format Stats for Table
            const currencyFormatter = new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR' });

            const statsData = [
                ['Total Customers', data.stats.totalCustomers.toString()],
                ['New Customers (Today)', data.stats.newCustomersToday.toString()],
                ['Total Revenue (Won)', currencyFormatter.format(data.stats.totalRevenue)],
                ['Won Deals (Today)', data.stats.wonDealsToday.toString()],
                ['Conversion Rate', `${data.stats.conversionRate.toFixed(1)}%`],
            ];

            autoTable(doc, {
                startY: 45,
                head: [['Metric', 'Value']],
                body: statsData,
                theme: 'striped',
                headStyles: { fillColor: [41, 128, 185], fontSize: 11 },
                styles: { fontSize: 10, cellPadding: 3 },
                columnStyles: { 0: { fontStyle: 'bold', cellWidth: 80 }, 1: { cellWidth: 'auto' } },
            });

            // 2. REVENUE TREND
            let finalY = (doc as any).lastAutoTable.finalY + 15;
            doc.text("Revenue Trend (Last 6 Months)", 14, finalY);

            const trendData = data.revenueTrend.map(item => [
                item.name,
                currencyFormatter.format(item.revenue)
            ]);

            autoTable(doc, {
                startY: finalY + 5,
                head: [['Month', 'Revenue']],
                body: trendData,
                theme: 'grid',
                headStyles: { fillColor: [39, 174, 96] },
            });

            // 3. SALES DISTRIBUTION
            finalY = (doc as any).lastAutoTable.finalY + 15;

            // Check if page break is needed
            if (finalY > 250) {
                doc.addPage();
                finalY = 20;
            }

            doc.text("Sales Team Performance", 14, finalY);

            const distributionData = data.salesDistribution.map(item => [
                item.salesName,
                item.customerCount.toString(),
                `${((item.customerCount / data.stats.totalCustomers) * 100).toFixed(1)}%`
            ]);

            autoTable(doc, {
                startY: finalY + 5,
                head: [['Sales Person', 'Assigned Customers', 'Share']],
                body: distributionData,
                theme: 'striped',
                headStyles: { fillColor: [142, 68, 173] },
            });

            // Footer
            const pageCount = (doc as any).internal.getNumberOfPages();
            for (let i = 1; i <= pageCount; i++) {
                doc.setPage(i);
                doc.setFontSize(8);
                doc.setTextColor(150);
                doc.text(`Page ${i} of ${pageCount}`, 190, 290, { align: 'right' });
                doc.text('Confidential - Generated by SalesCore AI', 14, 290);
            }

            doc.save(`SalesCore_Analytics_${format(new Date(), 'yyyy-MM-dd')}.pdf`);
            toast({ title: "Report Berhasil", description: "Laporan Analytics berhasil didownload." });

        } catch (error) {
            console.error('Export Error:', error);
            toast({ variant: "destructive", title: "Export Gagal", description: "Gagal membuat PDF." });
        } finally {
            setLoading(false);
        }
    };

    return (
        <Button
            onClick={handleExportPDF}
            disabled={!data || loading}
            variant="outline"
            className={className}
        >
            {loading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Download className="mr-2 h-4 w-4" />}
            Export PDF
        </Button>
    );
}
